/**
 * Renders every template in lib/templates.ts with emailmd and screenshots it
 * in headless Chromium, writing PNGs to public/ss/<id>.png — the images the
 * template gallery cards display. Also rewrites lib/screenshot-manifest.ts
 * with a content hash per PNG, which the cards append as ?v= so regenerated
 * screenshots bust next/image and browser caches.
 *
 * Run from apps/web:  npm run screenshots        (all templates)
 *                     npm run screenshots -- welcome invoice   (just those ids)
 */
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";
import { render } from "emailmd";
import { templates } from "../lib/templates.js";
import { screenshotVersions } from "../lib/screenshot-manifest.js";

// Captured at 720×600 CSS px (600px email + breathing room) at 2× for crisp
// gallery cards; the card crops from the top, so only the opening matters.
const VIEWPORT = { width: 720, height: 600 };

const outDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "../public/ss");
await mkdir(outDir, { recursive: true });

const only = process.argv.slice(2);
const selected = only.length ? templates.filter((t) => only.includes(t.id)) : templates;
const unknown = only.filter((id) => !templates.some((t) => t.id === id));
if (unknown.length) throw new Error(`Unknown template id(s): ${unknown.join(", ")}`);

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: VIEWPORT, deviceScaleFactor: 2 });

const versions: Record<string, string> = { ...screenshotVersions };

for (const template of selected) {
  const { html, warnings } = await render(template.markdown);
  for (const w of warnings ?? []) {
    console.warn(`  ⚠ ${template.id}: ${w.message}`);
  }
  await page.setContent(html, { waitUntil: "networkidle" });
  const file = path.join(outDir, `${template.id}.png`);
  await page.screenshot({ path: file });
  versions[template.id] = createHash("sha1").update(await readFile(file)).digest("hex").slice(0, 8);
  console.log(`✓ ${template.id} → public/ss/${template.id}.png`);
}

await browser.close();

const manifestFile = path.join(path.dirname(fileURLToPath(import.meta.url)), "../lib/screenshot-manifest.ts");
const entries = templates
  .filter((t) => versions[t.id])
  .map((t) => `  "${t.id}": "${versions[t.id]}",`)
  .join("\n");
await writeFile(
  manifestFile,
  `// Generated by scripts/generate-template-screenshots.mts — do not edit.\n// Content hash per gallery screenshot, used to cache-bust /ss/<id>.png.\nexport const screenshotVersions: Record<string, string> = {\n${entries}\n};\n`,
);
console.log(`\n${selected.length} screenshot(s) written to apps/web/public/ss/ (manifest updated)`);
