/**
 * Renders every template in lib/templates.ts with emailmd and screenshots it
 * in headless Chromium, writing PNGs to public/ss/<id>.png — the images the
 * template gallery cards display. Also rewrites lib/screenshot-manifest.ts
 * with a content hash per PNG, which the cards append as ?v= so regenerated
 * screenshots bust next/image and browser caches.
 *
 * Showcase entries (below) go through the same pipeline from standalone
 * markdown files, at their own viewport.
 *
 * Run from apps/web:  npm run screenshots        (all templates + showcase)
 *                     npm run screenshots -- welcome invoice   (just those ids)
 */
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";
import { render } from "emailmd";
import { templates } from "../lib/templates.js";
import { screenshotVersions } from "../lib/screenshot-manifest.js";

const here = path.dirname(fileURLToPath(import.meta.url));

// Captured at 720×600 CSS px (600px email + breathing room) at 2× for crisp
// gallery cards; the card crops from the top, so only the opening matters.
const VIEWPORT = { width: 720, height: 600 };

/**
 * One-off renders that fill a specific slot, such as a cell on the home page
 * or a section of the README, rather than a gallery card. They live as loose
 * markdown under showcase/ and are deliberately absent from lib/templates.ts,
 * so nothing links to them from /templates. Each one names the viewport it is
 * framed for, since these are composed to fit rather than cropped from the top.
 *
 * README images are served from imgs.emailmd.dev, not from this repo, so a new
 * PNG here has to be uploaded there before the README will show it.
 */
const showcase = [
  {
    id: "directive-showcase",
    file: "directives.md",
    viewport: { width: 720, height: 420 },
  },
  {
    id: "chart-showcase",
    file: "charts.md",
    viewport: { width: 600, height: 542 },
  },
];

const outDir = path.join(here, "../public/ss");
await mkdir(outDir, { recursive: true });

const only = process.argv.slice(2);
const known = [...templates.map((t) => t.id), ...showcase.map((s) => s.id)];
const unknown = only.filter((id) => !known.includes(id));
if (unknown.length) throw new Error(`Unknown id(s): ${unknown.join(", ")}`);

const jobs = [
  ...templates.map((t) => ({
    id: t.id,
    viewport: VIEWPORT,
    read: async () => t.markdown,
  })),
  ...showcase.map((s) => ({
    id: s.id,
    viewport: s.viewport,
    read: () => readFile(path.join(here, "../showcase", s.file), "utf8"),
  })),
].filter((job) => !only.length || only.includes(job.id));

const browser = await chromium.launch();
const versions: Record<string, string> = { ...screenshotVersions };

for (const job of jobs) {
  const page = await browser.newPage({
    viewport: job.viewport,
    deviceScaleFactor: 2,
  });
  const { html, warnings } = await render(await job.read());
  for (const w of warnings ?? []) {
    console.warn(`  ⚠ ${job.id}: ${w.message}`);
  }
  await page.setContent(html, { waitUntil: "networkidle" });
  const file = path.join(outDir, `${job.id}.png`);
  await page.screenshot({ path: file });
  await page.close();
  versions[job.id] = createHash("sha1")
    .update(await readFile(file))
    .digest("hex")
    .slice(0, 8);
  console.log(`✓ ${job.id} → public/ss/${job.id}.png`);
}

await browser.close();

const entries = [...templates.map((t) => t.id), ...showcase.map((s) => s.id)]
  .filter((id) => versions[id])
  .map((id) => `  "${id}": "${versions[id]}",`)
  .join("\n");
await writeFile(
  path.join(here, "../lib/screenshot-manifest.ts"),
  `// Generated by scripts/generate-template-screenshots.mts — do not edit.\n// Content hash per gallery screenshot, used to cache-bust /ss/<id>.png.\nexport const screenshotVersions: Record<string, string> = {\n${entries}\n};\n`,
);
console.log(`\n${jobs.length} screenshot(s) written to apps/web/public/ss/ (manifest updated)`);
