// Generated by scripts/generate-template-screenshots.mts — do not edit.
// Content hash per gallery screenshot, used to cache-bust /ss/<id>.png.
export const screenshotVersions: Record<string, string> = {
  "welcome": "78a1da3b",
  "password-reset": "211eef83",
  "order-confirmation": "faef5183",
  "newsletter": "19ebd518",
  "invoice": "0ea37251",
  "review-roundup": "5bbb7469",
  "rate-support": "f7115871",
  "confirm-email": "d8c2f267",
  "release-notes": "22dff23c",
  "event-invite": "70897613",
  "abandoned-cart": "f5ce0fe0",
  "product-announcement": "861c7092",
};
