// Generated by scripts/generate-template-screenshots.mts — do not edit.
// Content hash per gallery screenshot, used to cache-bust /ss/<id>.png.
export const screenshotVersions: Record<string, string> = {
  "password-reset": "211eef83",
  "order-confirmation": "ecf6382b",
  "newsletter": "19ebd518",
  "monthly-report": "2d2cb8f5",
  "invoice": "36aeaed4",
  "welcome": "78a1da3b",
  "review-roundup": "5bbb7469",
  "rate-support": "f7115871",
  "confirm-email": "d8c2f267",
  "release-notes": "22dff23c",
  "event-invite": "c2111631",
  "abandoned-cart": "d69d7489",
  "product-announcement": "861c7092",
};
